In [2]:
print("hello world")

hello world


## NUMPY

# numpy multiplication

In [3]:
import numpy as np

lst=[1,2,3,4,5]
array=np.array(lst)
result=array*2
print(result)

[ 2  4  6  8 10]


# numpy division

In [4]:
import numpy as np

lst=[4,8,12,16,20]
array=np.array(lst)
result=array//2
print(result)

[ 2  4  6  8 10]


# numpy addition

In [5]:
import numpy as np

lst=[1,2,3,4,5]
x=[4,8,10,12,16]
array1=np.array(lst)
array2=np.array(x)
result=array1+array2
print(result)

[ 5 10 13 16 21]


# numpy substraction

In [6]:
lst=[1,2,3,4,5]
x=[4,8,10,12,16]
array1=np.array(lst)
array2=np.array(x)
result=array2-array1
print(result)

[ 3  6  7  8 11]


#scalar arithemetic(mathemetic operation on single value)

In [7]:
arr=np.array([1,2,3,4,5])

print(arr + 1)
print(arr - 1)
print(arr * 2)
print(arr / 4)
print(arr ** 3)

[2 3 4 5 6]
[0 1 2 3 4]
[ 2  4  6  8 10]
[0.25 0.5  0.75 1.   1.25]
[  1   8  27  64 125]


##vector arithemetic(id array)

In [8]:
array=np.array([1,2,3,4,5,6])
array1=np.array([1.0,2.3,5.1,8.6])
print(np.sqrt(array))
print(np.round(array1))
print(np.floor(array1))
print(np.pi)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[1. 2. 5. 9.]
[1. 2. 5. 8.]
3.141592653589793


# 2 dimension array

In [9]:
import numpy as np

A=np.array([[1,2],
           [3,4]])

B=np.array([[5,6],
           [7,8]])

print(A.shape)
print(A*B)

(2, 2)
[[ 5 12]
 [21 32]]


# indexing

In [10]:
my_list= [[[1,2,3],[4,5,6],[7,8,9]]]
print(my_list)
print(my_list[0][1][1])

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]
5


In [11]:
new_arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
#new_arr = new_arr*2
print(new_arr)
print(new_arr[0][0])
#check how many dimensions the arrays have:
print(new_arr.ndim)
print(new_arr.shape)
print(new_arr[0][0][1]+new_arr[0][1][0])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[1 2 3]
3
(1, 3, 3)
6


# multiple a nested list by 5 using numpy

In [12]:
nested_list = [
	[1,2,3],
	[4,5,6],
	[7,8,9]
]

result = np.array(nested_list)
result = result*5
print(result)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [13]:
nested_list = [
	[1,2,3],
	[4,5,6],
	[7,8,9]
]

print(nested_list[0]+nested_list[1])

new_result = np.array(nested_list)
print(new_result[0] + new_result[1])

[1, 2, 3, 4, 5, 6]
[5 7 9]


# slicing

In [14]:
import numpy as np

lst= [1,2,3,4,5,6,7,8,9]
result = np.array(lst)


print("1. result[1:8] - Elements from index 1 to 7:", result[1:8])
print("2. result[1:]  -Elements from index 1 to end:",
result[1:])
print("3. result[:1] - Elements from start to index 0:", result[::-1])


1. result[1:8] - Elements from index 1 to 7: [2 3 4 5 6 7 8]
2. result[1:]  -Elements from index 1 to end: [2 3 4 5 6 7 8 9]
3. result[:1] - Elements from start to index 0: [9 8 7 6 5 4 3 2 1]


# negative slicing

In [15]:
import numpy as np 

arr = np.array([1,2,3,4,5,6,7])

print("4. arr[-3:-1] - from 3rd last to 2nd last element:", arr[-3:-1])
print("5. arr[::3] - every 3rd element:", arr[::3])

4. arr[-3:-1] - from 3rd last to 2nd last element: [5 6]
5. arr[::3] - every 3rd element: [1 4 7]


# slicing 2D array

In [16]:
nested_list = [
	[1,2,3,5,9,8],
	[4,5,6,7,8,9]
]


#---------slicing Row && Column--------#

new_arr = np.array(nested_list)


print(new_arr[0, 0:4])
print(new_arr[0:2, 5])
print(new_arr[0:2, 1:4])


[1 2 3 5]
[8 9]
[[2 3 5]
 [5 6 7]]
