In [2]:
print("hello world")

hello world


## NUMPY

# numpy multiplication

In [3]:
import numpy as np

lst=[1,2,3,4,5]
array=np.array(lst)
result=array*2
print(result)

[ 2  4  6  8 10]


# numpy division

In [4]:
import numpy as np

lst=[4,8,12,16,20]
array=np.array(lst)
result=array//2
print(result)

[ 2  4  6  8 10]


# numpy addition

In [5]:
import numpy as np

lst=[1,2,3,4,5]
x=[4,8,10,12,16]
array1=np.array(lst)
array2=np.array(x)
result=array1+array2
print(result)

[ 5 10 13 16 21]


# numpy substraction

In [6]:
lst=[1,2,3,4,5]
x=[4,8,10,12,16]
array1=np.array(lst)
array2=np.array(x)
result=array2-array1
print(result)

[ 3  6  7  8 11]


#scalar arithemetic(mathemetic operation on single value)

In [7]:
arr=np.array([1,2,3,4,5])

print(arr + 1)
print(arr - 1)
print(arr * 2)
print(arr / 4)
print(arr ** 3)

[2 3 4 5 6]
[0 1 2 3 4]
[ 2  4  6  8 10]
[0.25 0.5  0.75 1.   1.25]
[  1   8  27  64 125]


##vector arithemetic(id array)

In [8]:
array=np.array([1,2,3,4,5,6])
array1=np.array([1.0,2.3,5.1,8.6])
print(np.sqrt(array))
print(np.round(array1))
print(np.floor(array1))
print(np.pi)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[1. 2. 5. 9.]
[1. 2. 5. 8.]
3.141592653589793


# 2 dimension array

In [9]:
import numpy as np

A=np.array([[1,2],
           [3,4]])

B=np.array([[5,6],
           [7,8]])

print(A.shape)
print(A*B)

(2, 2)
[[ 5 12]
 [21 32]]


# indexing

In [10]:
my_list= [[[1,2,3],[4,5,6],[7,8,9]]]
print(my_list)
print(my_list[0][1][1])

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]
5


In [11]:
new_arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
#new_arr = new_arr*2
print(new_arr)
print(new_arr[0][0])
#check how many dimensions the arrays have:
print(new_arr.ndim)
print(new_arr.shape)
print(new_arr[0][0][1]+new_arr[0][1][0])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[1 2 3]
3
(1, 3, 3)
6


# multiple a nested list by 5 using numpy

In [12]:
nested_list = [
	[1,2,3],
	[4,5,6],
	[7,8,9]
]

result = np.array(nested_list)
result = result*5
print(result)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [13]:
nested_list = [
	[1,2,3],
	[4,5,6],
	[7,8,9]
]

print(nested_list[0]+nested_list[1])

new_result = np.array(nested_list)
print(new_result[0] + new_result[1])

[1, 2, 3, 4, 5, 6]
[5 7 9]


# slicing

In [14]:
import numpy as np

lst= [1,2,3,4,5,6,7,8,9]
result = np.array(lst)


print("1. result[1:8] - Elements from index 1 to 7:", result[1:8])
print("2. result[1:]  -Elements from index 1 to end:",
result[1:])
print("3. result[:1] - Elements from start to index 0:", result[::-1])


1. result[1:8] - Elements from index 1 to 7: [2 3 4 5 6 7 8]
2. result[1:]  -Elements from index 1 to end: [2 3 4 5 6 7 8 9]
3. result[:1] - Elements from start to index 0: [9 8 7 6 5 4 3 2 1]


# negative slicing

In [15]:
import numpy as np 

arr = np.array([1,2,3,4,5,6,7])

print("4. arr[-3:-1] - from 3rd last to 2nd last element:", arr[-3:-1])
print("5. arr[::3] - every 3rd element:", arr[::3])

4. arr[-3:-1] - from 3rd last to 2nd last element: [5 6]
5. arr[::3] - every 3rd element: [1 4 7]


# slicing 2D array

In [16]:
nested_list = [
	[1,2,3,5,9,8],
	[4,5,6,7,8,9]
]


#---------slicing Row && Column--------#

new_arr = np.array(nested_list)


print(new_arr[0, 0:4])
print(new_arr[0:2, 5])
print(new_arr[0:2, 1:4])


[1 2 3 5]
[8 9]
[[2 3 5]
 [5 6 7]]


# numpy slicing qns

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

# Q1a: Slice from index 2 to 5
print(arr[2:6])

# Q1b: Slice from index 3 to the end
print(arr[3:])

# Q1c: Slice from start to index 4 (exclusive)
print(arr[:4])


[30 40 50 60]
[40 50 60 70 80]
[10 20 30 40]


# numpy negative slicing qns

In [2]:
arr = np.array([5, 10, 15, 20, 25, 30, 35])

# Q2a: Get the last 3 elements
print(arr[-3:])

# Q2b: Get elements from 3rd last to 2nd last (exclusive)
print(arr[-3:-2])

[25 30 35]
[25]


# numpy step slicing qns

In [3]:
arr = np.array([2, 4, 6, 8, 10, 12, 14, 16])
# Q3a: Every 2nd element
print(arr[::2])

# Q3b: Every 3rd element starting from index 1
print(arr[1::3])


[ 2  6 10 14]
[ 4 10 16]


# matrix multiplication

Matrix multiplication is how the network learns and transforms data.

Matrix multiplication is used in AI to combine many input features with 
weights at once to produce outputs — this is how neural networks make predictions.

This is how a neural network layer works:
inputs × weights → outputs

In [4]:
import numpy as np

A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print(np.matmul(A,B))
print(A@B)
print(A. dot(B))






[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


# 1*3 multiplication

no of columns in first numpy array = no of rows in second numpy array

In [7]:
import numpy as np

x = np.array([[170,65,20]])
w = np.array([
	[0.2,0.4],
	[0.5,0.1],
	[0.3,0.7]

])

output = x@w
print(output)



[[72.5 88.5]]


# concatenate

In [8]:
import numpy as np

A = np.array([[1, 2, 3]])
B = np.array([[4, 5, 6]])
C = np.concatenate((A,B), axis=0)#row_wise concatenate
print(C)
C = np.concatenate((A,B), axis=1)#column_wise concatenate
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]


# Aggregate function

  Aggregate functions are used to summarize data.
  They usually take an array as input and return a single value (or summary).
  Examples: sum, mean, max, min, argmin, argmax, etc

In [9]:
import numpy as np

# Create a 2D numpy array (2 rows * 5 columns)
array = np.array([
	[1, 2, 3, 4, 5],
	[6, 7, 8, 9, 10]
])


print("Sum of all elements:", np.sum(array))
print("Mean (average):", np.mean(array))

print("Maximum value:", np.max(array))
print("minimum value:", np.min(array))

print("Index of minimum value:", np.argmin(array))
print("Index of maximum value:", np.argmax(array))

Sum of all elements: 55
Mean (average): 5.5
Maximum value: 10
minimum value: 1
Index of minimum value: 0
Index of maximum value: 9


# sum across column and rows

In [11]:
import numpy as np

array = np.array([
	[1,2,3,4,5],
	[6,7,8,9,10]
])

#Sum across Columns (axis=0)
print("Column-wise sum:", np.sum(array, axis=0))

#Sum across Rows (axis=1)
print("Row-wise sum:", np.sum(array, axis=1))

Column-wise sum: [ 7  9 11 13 15]
Row-wise sum: [15 40]


In [12]:
import numpy as np

array = np.array([
	[1,2,3,4,5],
	[6,7,8,9,10]
])

#product of all elements
print("product of all elements:", np.prod(array))

#count of an array
print(array.size)

#how to create a random array

rand_array = np.random.randint(1, 101, size=5)
print(rand_array)



product of all elements: 3628800
10
[56 58  2 50 58]


# reshaped array

In [13]:
import numpy as np

#reshaped() - change the shape of an array

arr = np.array([1, 2, 3, 4, 5, 6])
#print(arr.shape)
reshaped = arr.reshape(2, 3)
print("reshaped(): \n", reshaped)

reshaped(): 
 [[1 2 3]
 [4 5 6]]


# flatten()

In [14]:
import numpy as np

#flatten() - convert multi-dimentional array into 1D array

arr2D = np.array([[1, 2, 3], [4, 5, 6]])
flat = arr2D.flatten()
print("flattened(): \n", flat)

flattened(): 
 [1 2 3 4 5 6]


In [15]:
import numpy as np

#ravelled() - convert multi-dimentional array into 1D array

arr2D = np.array([[1, 2, 3], [4, 5, 6]])
ravelled = arr2D.ravel()
print("ravel():", ravelled)

ravel(): [1 2 3 4 5 6]


# transposed

In [16]:
import numpy as np

arr2D = np.array([[1, 2, 3], [4, 5, 6]])
transposed = arr2D.transpose()
print("transposed(): \n", transposed)

transposed(): 
 [[1 4]
 [2 5]
 [3 6]]


# vstack and hstack

In [17]:
a=np.array([1,2,3])
b=np.array([4,5,6])

vertical = np.vstack((a,b))
horizontal = np.hstack((a,b))
print("Vertical stack:\n", vertical)#row-wise
print("Horizontal stack:\n", horizontal)#column-wise

Vertical stack:
 [[1 2 3]
 [4 5 6]]
Horizontal stack:
 [1 2 3 4 5 6]


# split method()

split an array into multiple parts

In [18]:
arr = np.array([1,2,3,4,5,6,7,8,9])
parts = np.split(arr, 3)
print("split():", parts)

split(): [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


# unique()

find unique elements in an array


In [19]:
arr = np.array([1,2,2,3,4,4,5])
unique_values = np.unique(arr)
print("unique():", unique_values)

unique(): [1 2 3 4 5]


# numpy filtering()

In [23]:
array = np.array([
    [50, 60, 40, 89, 90],
    [89, 78, 56, 75, 99]
])



marks = array[array > 40]
print("All marks > 40:",marks)

new_marks = array[(array > 40) & (array < 90)]
print("Marks between 40 and 90:",new_marks)

new_marks = array[(array > 40) | (array < 90)]
print("Marks between 40 and 90:",new_marks)





All marks > 40: [50 60 89 90 89 78 56 75 99]
Marks between 40 and 90: [50 60 89 89 78 56 75]
Marks between 40 and 90: [50 60 40 89 90 89 78 56 75 99]
